"""Initial migration

Revision ID: f6140cf0fe77
Revises: 
Create Date: 2024-10-01 09:58:27.013387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6140cf0fe77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('breeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_breeds_id'), 'breeds', ['id'], unique=False)
    op.create_index(op.f('ix_breeds_name'), 'breeds', ['name'], unique=True)
    op.create_table('kittens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('age_months', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('breed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['breed_id'], ['breeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kittens_id'), 'kittens', ['id'], unique=False)
    op.create_index(op.f('ix_kittens_name'), 'kittens', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_kittens_name'), table_name='kittens')
    op.drop_index(op.f('ix_kittens_id'), table_name='kittens')
    op.drop_table('kittens')
    op.drop_index(op.f('ix_breeds_name'), table_name='breeds')
    op.drop_index(op.f('ix_breeds_id'), table_name='breeds')
    op.drop_table('breeds')
    # ### end Alembic commands ###
